import { BenchmarkComparisonData, NoCConfig, SweepPoint, WorkloadType } from '../types/noc';

export function getInitialBenchmarkData(config: NoCConfig): BenchmarkComparisonData {
  const rates = [0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.55, 0.60];

  const makeCurve = (
    baseLat: number,
    slope: number,
    cliffRate: number,
    tputMax: number,
    baseEnergy: number
  ): SweepPoint[] => {
    return rates.map((rate) => {
      const isPastCliff = rate > cliffRate;
      const saturationFactor = isPastCliff ? Math.pow((rate - cliffRate) * 7.5, 2.2) : 0;
      const avgLat = Number((baseLat + rate * slope + saturationFactor * 16).toFixed(2));
      const tput = Number(Math.min(tputMax, rate * (isPastCliff ? 0.78 : 0.98)).toFixed(4));
      const energyPerFlit = Number((baseEnergy + rate * 0.8 + (isPastCliff ? 1.4 : 0)).toFixed(2));
      const bufferOcc = Number(Math.min(96, Math.max(4, rate * 120 + saturationFactor * 40)).toFixed(1));

      return {
        injectionRate: rate,
        avgLatency: avgLat,
        maxLatency: Number((avgLat * (2.2 + saturationFactor * 0.8)).toFixed(2)),
        tailLatencyP99: Number((avgLat * 1.85).toFixed(2)),
        throughput: tput,
        bufferOccupancyPct: bufferOcc,
        energyPerFlitPJ: energyPerFlit,
        energyDelayProduct: Number((avgLat * energyPerFlit).toFixed(2)),
        isSaturated: isPastCliff,
      };
    });
  };

  return {
    injectionRates: rates,
    results: {
      BASELINE_XY: makeCurve(4.8, 14.0, 0.30, 0.29, 2.2),
      ADAPTIVE_DYXY: makeCurve(4.6, 10.5, 0.40, 0.38, 2.3),
      CONGESTION_AWARE_RCA: makeCurve(5.1, 8.5, 0.45, 0.42, 2.5),
      LOW_POWER_BYPASS: makeCurve(4.2, 18.0, 0.25, 0.24, 1.7),
      PROPOSED_RECONFIGURABLE: makeCurve(4.3, 7.2, 0.50, 0.48, 2.0),
    },
  };
}

export function getInitialWorkloadSensitivity(config: NoCConfig) {
  return [
    {
      workload: 'CNN (Local Systolic)',
      workloadId: 'CNN_LOCAL' as WorkloadType,
      desc: 'Nearest-neighbor Conv2D dataflow',
      baselineXY: {
        injectionRate: 0.35,
        avgLatency: 12.4,
        maxLatency: 34.2,
        tailLatencyP99: 25.1,
        throughput: 0.32,
        bufferOccupancyPct: 56.4,
        energyPerFlitPJ: 2.4,
        energyDelayProduct: 29.76,
        isSaturated: false,
      },
      adaptive: {
        injectionRate: 0.35,
        avgLatency: 8.6,
        maxLatency: 22.1,
        tailLatencyP99: 16.4,
        throughput: 0.34,
        bufferOccupancyPct: 38.2,
        energyPerFlitPJ: 2.35,
        energyDelayProduct: 20.21,
        isSaturated: false,
      },
      congestionAware: {
        injectionRate: 0.35,
        avgLatency: 9.4,
        maxLatency: 24.8,
        tailLatencyP99: 18.2,
        throughput: 0.33,
        bufferOccupancyPct: 41.5,
        energyPerFlitPJ: 2.6,
        energyDelayProduct: 24.44,
        isSaturated: false,
      },
      proposed: {
        injectionRate: 0.35,
        avgLatency: 7.8,
        maxLatency: 19.5,
        tailLatencyP99: 14.8,
        throughput: 0.345,
        bufferOccupancyPct: 32.1,
        energyPerFlitPJ: 2.1,
        energyDelayProduct: 16.38,
        isSaturated: false,
      },
      latencyReductionPct: 37.1,
      throughputGainPct: 7.8,
      edpImprovementPct: 44.9,
    },
    {
      workload: 'Transformer (Global Attention)',
      workloadId: 'TRANSFORMER_GLOBAL' as WorkloadType,
      desc: 'All-to-all QKV broadcast & embeddings',
      baselineXY: {
        injectionRate: 0.35,
        avgLatency: 18.2,
        maxLatency: 52.0,
        tailLatencyP99: 41.0,
        throughput: 0.28,
        bufferOccupancyPct: 78.5,
        energyPerFlitPJ: 3.1,
        energyDelayProduct: 56.42,
        isSaturated: true,
      },
      adaptive: {
        injectionRate: 0.35,
        avgLatency: 13.5,
        maxLatency: 36.2,
        tailLatencyP99: 28.4,
        throughput: 0.32,
        bufferOccupancyPct: 54.0,
        energyPerFlitPJ: 3.0,
        energyDelayProduct: 40.5,
        isSaturated: false,
      },
      congestionAware: {
        injectionRate: 0.35,
        avgLatency: 9.8,
        maxLatency: 26.0,
        tailLatencyP99: 20.1,
        throughput: 0.345,
        bufferOccupancyPct: 39.8,
        energyPerFlitPJ: 3.2,
        energyDelayProduct: 31.36,
        isSaturated: false,
      },
      proposed: {
        injectionRate: 0.35,
        avgLatency: 9.2,
        maxLatency: 23.4,
        tailLatencyP99: 18.2,
        throughput: 0.348,
        bufferOccupancyPct: 36.4,
        energyPerFlitPJ: 2.8,
        energyDelayProduct: 25.76,
        isSaturated: false,
      },
      latencyReductionPct: 49.5,
      throughputGainPct: 24.3,
      edpImprovementPct: 54.3,
    },
    {
      workload: 'MoE (Sparse Bursty)',
      workloadId: 'MOE_BURSTY' as WorkloadType,
      desc: 'Expert router token bursts',
      baselineXY: {
        injectionRate: 0.35,
        avgLatency: 15.6,
        maxLatency: 44.0,
        tailLatencyP99: 35.0,
        throughput: 0.30,
        bufferOccupancyPct: 69.2,
        energyPerFlitPJ: 2.8,
        energyDelayProduct: 43.68,
        isSaturated: true,
      },
      adaptive: {
        injectionRate: 0.35,
        avgLatency: 11.2,
        maxLatency: 29.5,
        tailLatencyP99: 23.0,
        throughput: 0.33,
        bufferOccupancyPct: 47.0,
        energyPerFlitPJ: 2.7,
        energyDelayProduct: 30.24,
        isSaturated: false,
      },
      congestionAware: {
        injectionRate: 0.35,
        avgLatency: 10.4,
        maxLatency: 27.2,
        tailLatencyP99: 21.5,
        throughput: 0.34,
        bufferOccupancyPct: 43.1,
        energyPerFlitPJ: 2.9,
        energyDelayProduct: 30.16,
        isSaturated: false,
      },
      proposed: {
        injectionRate: 0.35,
        avgLatency: 8.9,
        maxLatency: 22.0,
        tailLatencyP99: 17.5,
        throughput: 0.346,
        bufferOccupancyPct: 35.2,
        energyPerFlitPJ: 2.4,
        energyDelayProduct: 21.36,
        isSaturated: false,
      },
      latencyReductionPct: 42.9,
      throughputGainPct: 15.3,
      edpImprovementPct: 51.1,
    },
    {
      workload: 'Hotspot (Accelerator Core)',
      workloadId: 'HOTSPOT_TRAFFIC' as WorkloadType,
      desc: 'Centralized memory/compute sink',
      baselineXY: {
        injectionRate: 0.35,
        avgLatency: 22.4,
        maxLatency: 68.0,
        tailLatencyP99: 54.0,
        throughput: 0.25,
        bufferOccupancyPct: 88.0,
        energyPerFlitPJ: 3.4,
        energyDelayProduct: 76.16,
        isSaturated: true,
      },
      adaptive: {
        injectionRate: 0.35,
        avgLatency: 15.0,
        maxLatency: 41.0,
        tailLatencyP99: 32.0,
        throughput: 0.31,
        bufferOccupancyPct: 62.0,
        energyPerFlitPJ: 3.2,
        energyDelayProduct: 48.0,
        isSaturated: false,
      },
      congestionAware: {
        injectionRate: 0.35,
        avgLatency: 10.9,
        maxLatency: 28.5,
        tailLatencyP99: 22.0,
        throughput: 0.34,
        bufferOccupancyPct: 44.0,
        energyPerFlitPJ: 3.3,
        energyDelayProduct: 35.97,
        isSaturated: false,
      },
      proposed: {
        injectionRate: 0.35,
        avgLatency: 9.8,
        maxLatency: 25.0,
        tailLatencyP99: 19.5,
        throughput: 0.347,
        bufferOccupancyPct: 38.0,
        energyPerFlitPJ: 2.8,
        energyDelayProduct: 27.44,
        isSaturated: false,
      },
      latencyReductionPct: 56.2,
      throughputGainPct: 38.8,
      edpImprovementPct: 64.0,
    },
    {
      workload: 'Uniform Random',
      workloadId: 'UNIFORM_RANDOM' as WorkloadType,
      desc: 'Uniform baseline synthetic traffic',
      baselineXY: {
        injectionRate: 0.35,
        avgLatency: 11.2,
        maxLatency: 28.0,
        tailLatencyP99: 21.0,
        throughput: 0.33,
        bufferOccupancyPct: 45.0,
        energyPerFlitPJ: 2.3,
        energyDelayProduct: 25.76,
        isSaturated: false,
      },
      adaptive: {
        injectionRate: 0.35,
        avgLatency: 9.8,
        maxLatency: 24.5,
        tailLatencyP99: 18.0,
        throughput: 0.34,
        bufferOccupancyPct: 39.0,
        energyPerFlitPJ: 2.4,
        energyDelayProduct: 23.52,
        isSaturated: false,
      },
      congestionAware: {
        injectionRate: 0.35,
        avgLatency: 10.2,
        maxLatency: 25.5,
        tailLatencyP99: 19.0,
        throughput: 0.335,
        bufferOccupancyPct: 40.5,
        energyPerFlitPJ: 2.6,
        energyDelayProduct: 26.52,
        isSaturated: false,
      },
      proposed: {
        injectionRate: 0.35,
        avgLatency: 8.8,
        maxLatency: 21.0,
        tailLatencyP99: 16.0,
        throughput: 0.346,
        bufferOccupancyPct: 34.0,
        energyPerFlitPJ: 2.1,
        energyDelayProduct: 18.48,
        isSaturated: false,
      },
      latencyReductionPct: 21.4,
      throughputGainPct: 4.8,
      edpImprovementPct: 28.3,
    },
  ];
}
